### ISSUE TITLE
simpleBamCaller no longer available?

### ISSUE THREAD

**Issue by TaurVil** [stschiff/GAworkshop#4]
Hello, I found this workshop very helpful to understand some of the processing of ancient genomic data. However, it seems that simpleBamCaller is no longer available as part of the sequenceTools project. Is the functionality still present and, if so, how might one use it? Thanks!

**Comment by stschiff** [comment]
simpleBamCaller is no longer supported, but `pileupCaller` does everything that's needed. Have a look under https://github.com/stschiff/sequenceTools
